### ISSUE TITLE
演示的页面很好啊，但是我用给出的网页demo命令跑还是以前的旧版本，请问是哪里不对吗

### ISSUE THREAD

**Issue by Shimada666** [vicanso/diving-rs#1]
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/33391300/225594127-7c19f214-9224-452e-8330-fa567d940af3.png">
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/33391300/225594195-f1be2fcf-3c74-4311-b4cf-5b83016f5c0c.png">

另外命令如果不挂载 docker.sock 的话会一直返回 exit status: 1，所以我使用的命令是：

```shell
docker run -d --restart=always \ 
  -v /var/run/docker.sock:/var/run/docker.sock \ 
  -v $PWD/diving:/home/rust/.diving \ 
  --name diving \  
  -p 7001:7001 \ 
  vicanso/diving
```

**Comment by vicanso** [comment]
你没重新`docker pull vicanso/diving`吧？或者直接指定`vicanso/diving:0.2.0` 这个版本的镜像。

```bash
docker run -d --restart=always \
  -p 7001:7001 \
  -v $PWD/diving:/home/rust/.diving \
  --name=diving \
  vicanso/diving:0.2.0
```

**Comment by Shimada666** [comment]
> 你没重新`docker pull vicanso/diving`吧？或者直接指定`vicanso/diving:0.2.0` 这个版本的镜像。
> 
> ```shell
> docker run -d --restart=always \
>   -p 7001:7001 \
>   -v $PWD/diving:/home/rust/.diving \
>   --name=diving \
>   vicanso/diving:0.2.0
> ```

感谢，确实是忘了删除镜像。但是遇到了新问题：网页版永远是 error
<img width="1965" alt="image" src="https://user-images.githubusercontent.com/33391300/225821424-c5088486-dd27-44d6-ae2e-8542b5901f81.png">

但我使用命令行测试没问题
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/33391300/225821539-534d4d3b-dc44-43d2-962d-4c7dce24895f.png">

使用的命令就是你刚刚给我的命令

**Comment by vicanso** [comment]
部署的服务器是否无访问`https://index.docker.io/v2`的权限？程序通过直接访问docker http api的形式拉取镜像数据，因此需要有对应访问其网络的权限，如果是访问私有化部署的源也一样。
如果部署的服务器网络没问题，看看可否查看一下镜像的运行日志？

**Comment by Shimada666** [comment]
访问看起来没用问题，在日志中找到了一些错误，说是文件已存在？
```
2023-03-17T16:26:41.832472Z  INFO diving::middleware: category="accessLog" ip="127.0.0.1" method="GET" uri="/ping" status=200 cost=0
2023-03-17T16:26:51.918397Z  INFO diving::middleware: category="accessLog" ip="127.0.0.1" method="GET" uri="/ping" status=200 cost=0
2023-03-17T16:27:00.987400Z  INFO diving::middleware: category="accessLog" ip="172.17.0.1" method="GET" uri="/" status=200 cost=3
2023-03-17T16:27:01.002721Z  INFO diving::middleware: category="accessLog" ip="172.17.0.1" method="GET" uri="/assets/ui-b13912fd.js" status=200 cost=0
2023-03-17T16:27:01.142518Z  INFO diving::middleware: category="accessLog" ip="172.17.0.1" method="GET" uri="/assets/antd-37923b5e.js" status=200 cost=0
2023-03-17T16:27:02.011711Z  INFO diving::middleware: category="accessLog" ip="127.0.0.1" method="GET" uri="/ping" status=200 cost=0
2023-03-17T16:27:04.875772Z  INFO diving::image::docker: Getting token url="https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/redis:pull"
2023-03-17T16:27:06.878613Z  INFO diving::image::docker: Got token url="https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/redis:pull"
2023-03-17T16:27:06.878877Z  INFO diving::image::docker: Getting manifest url="https://index.docker.io/v2/library/redis/manifests/latest"
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/config/load_config.rs:35:49
2023-03-17T16:27:08.289647Z  INFO diving::image::docker: Got manifest url="https://index.docker.io/v2/library/redis/manifests/latest"
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/config/load_config.rs:35:49
2023-03-17T16:27:12.070515Z  INFO diving::middleware: category="accessLog" ip="127.0.0.1" method="GET" uri="/ping" status=200 cost=0
```

**Comment by Shimada666** [comment]
感谢，可以了，是我理解错了，把 macos 上的 diving 挂了进去，其实镜像里自带了 diving。打扰了哈

**Comment by vicanso** [comment]
应该是挂载之后创建缓存数据的目录`.diving`失败了，晚点我试试在macos使用镜像运行看看，之前只在linux运行，没测试macos的

**Comment by vicanso** [comment]
@Shimada666 是由于镜像运行时使用非root用户，而挂载至镜像的目录无权限导致的，后面版本调整为启动时校验权限
